"""PKCE (RFC 7636) — Proof Key for Code Exchange.

The attack PKCE stops: an authorization code travels through the browser
(history, referrer headers, proxies). If a public client (no secret) receives
that code, an interceptor can redeem it. PKCE makes the code useless without
the verifier, which never leaves the client's back channel:

    attacker has:  code, client_id, redirect_uri
    attacker needs: code_verifier  → only exists client-side, sent via TLS
                  to /token directly, never through the browser

We implement S256 only. `plain` (challenge == verifier) provides zero
protection against a code interceptor and OAuth 2.1 forbids it — which is
why discovery advertises S256 exclusively.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import secrets


def generate_verifier() -> str:
    """43-128 char high-entropy string (RFC 7636 §4.1).

    token_urlsafe(48) → 64 chars from [A-Za-z0-9_-]: comfortably in range,
    generated by the CSPRNG — never derive verifiers from math.random or
    timestamps."""
    return secrets.token_urlsafe(48)


def challenge_s256(verifier: str) -> str:
    """BASE64URL-ENCODE(SHA256(ASCII(verifier))) — RFC 7636 §4.2."""
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    return base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")


def verify_challenge(verifier: str, stored_challenge: str, method: str) -> bool:
    """Constant-time verification of a redemption attempt.

    - method must be exactly S256: a stored 'plain' challenge would let an
      attacker who intercepted the *challenge* (it's in the authorize URL!)
      redeem directly — accepting plain silently defeats PKCE.
    - compare_digest: no timing side-channel on the comparison itself.
    """
    if method != "S256":
        return False
    if not verifier or not (43 <= len(verifier) <= 128):
        return False
    try:
        expected = challenge_s256(verifier)
    except (UnicodeEncodeError, ValueError):
        return False
    return hmac.compare_digest(expected, stored_challenge)
